
export const UptrackerCountryCodes = {
  us: {name: 'United States', dial_code: '+1', code: 'us'},
  ca: {name: 'Canada', dial_code: '+1', code: 'ca'},
  au: {name: 'Australia', dial_code: '+61', code: 'au'},
  nz: {name: 'New Zealand', dial_code: '+64', code: 'nz'}
};

export const AllCountryCodes = {
  us: {name: 'United States', dial_code: '+1', code: 'us'},
  ad: {name: 'Andorra', dial_code: '+376', code: 'ad'},
  ae: {name: 'United Arab Emirates', dial_code: '+971', code: 'ae'},
  af: {name: 'Afghanistan', dial_code: '+93', code: 'af'},
  ag: {name: 'Antigua and Barbuda', dial_code: '+1268', code: 'ag'},
  ai: {name: 'Anguilla', dial_code: '+1 264', code: 'ai'},
  al: {name: 'Albania', dial_code: '+355', code: 'al'},
  am: {name: 'Armenia', dial_code: '+374', code: 'am'},
  ao: {name: 'Angola', dial_code: '+244', code: 'ao'},
  aq: {name: 'Antarctica', dial_code: null, code: 'aq'},
  ar: {name: 'Argentina', dial_code: '+54', code: 'ar'},
  as: {name: 'AmericanSamoa', dial_code: '+1 684', code: 'as'},
  at: {name: 'Austria', dial_code: '+43', code: 'at'},
  au: {name: 'Australia', dial_code: '+61', code: 'au'},
  aw: {name: 'Aruba', dial_code: '+297', code: 'aw'},
  ax: {name: 'land Islands', dial_code: '', code: 'ax'},
  az: {name: 'Azerbaijan', dial_code: '+994', code: 'az'},
  ba: {name: 'Bosnia and Herzegovina', dial_code: '+387', code: 'ba'},
  bb: {name: 'Barbados', dial_code: '+1 246', code: 'bb'},
  bd: {name: 'Bangladesh', dial_code: '+880', code: 'bd'},
  be: {name: 'Belgium', dial_code: '+32', code: 'be'},
  bf: {name: 'Burkina Faso', dial_code: '+226', code: 'bf'},
  bg: {name: 'Bulgaria', dial_code: '+359', code: 'bg'},
  bh: {name: 'Bahrain', dial_code: '+973', code: 'bh'},
  bi: {name: 'Burundi', dial_code: '+257', code: 'bi'},
  bj: {name: 'Benin', dial_code: '+229', code: 'bj'},
  bl: {name: 'Saint Barthélemy', dial_code: '+590', code: 'bl'},
  bm: {name: 'Bermuda', dial_code: '+1 441', code: 'bm'},
  bn: {name: 'Brunei Darussalam', dial_code: '+673', code: 'bn'},
  bo: {name: 'Bolivia, Plurinational State of', dial_code: '+591', code: 'bo'},
  br: {name: 'Brazil', dial_code: '+55', code: 'br'},
  bs: {name: 'Bahamas', dial_code: '+1 242', code: 'bs'},
  bt: {name: 'Bhutan', dial_code: '+975', code: 'bt'},
  bw: {name: 'Botswana', dial_code: '+267', code: 'bw'},
  by: {name: 'Belarus', dial_code: '+375', code: 'by'},
  bz: {name: 'Belize', dial_code: '+501', code: 'bz'},
  ca: {name: 'Canada', dial_code: '+1', code: 'ca'},
  cc: {name: 'Cocos (Keeling) Islands', dial_code: '+61', code: 'cc'},
  cd: {name: 'Congo, The Democratic Republic of the', dial_code: '+243', code: 'cd'},
  cf: {name: 'Central African Republic', dial_code: '+236', code: 'cf'},
  cg: {name: 'Congo', dial_code: '+242', code: 'cg'},
  ch: {name: 'Switzerland', dial_code: '+41', code: 'ch'},
  ci: {name: 'Cote d`Ivoire', dial_code: '+225', code: 'ci'},
  ck: {name: 'Cook Islands', dial_code: '+682', code: 'ck'},
  cl: {name: 'Chile', dial_code: '+56', code: 'cl'},
  cm: {name: 'Cameroon', dial_code: '+237', code: 'cm'},
  cn: {name: 'China', dial_code: '+86', code: 'cn'},
  co: {name: 'Colombia', dial_code: '+57', code: 'co'},
  cr: {name: 'Costa Rica', dial_code: '+506', code: 'cr'},
  cu: {name: 'Cuba', dial_code: '+53', code: 'cu'},
  cv: {name: 'Cape Verde', dial_code: '+238', code: 'cv'},
  cx: {name: 'Christmas Island', dial_code: '+61', code: 'cx'},
  cy: {name: 'Cyprus', dial_code: '+537', code: 'cy'},
  cz: {name: 'Czech Republic', dial_code: '+420', code: 'cz'},
  de: {name: 'Germany', dial_code: '+49', code: 'de'},
  dj: {name: 'Djibouti', dial_code: '+253', code: 'dj'},
  dk: {name: 'Denmark', dial_code: '+45', code: 'dk'},
  dm: {name: 'Dominica', dial_code: '+1 767', code: 'dm'},
  dz: {name: 'Algeria', dial_code: '+213', code: 'dz'},
  ec: {name: 'Ecuador', dial_code: '+593', code: 'ec'},
  ee: {name: 'Estonia', dial_code: '+372', code: 'ee'},
  eg: {name: 'Egypt', dial_code: '+20', code: 'eg'},
  er: {name: 'Eritrea', dial_code: '+291', code: 'er'},
  es: {name: 'Spain', dial_code: '+34', code: 'es'},
  et: {name: 'Ethiopia', dial_code: '+251', code: 'et'},
  fi: {name: 'Finland', dial_code: '+358', code: 'fi'},
  fj: {name: 'Fiji', dial_code: '+679', code: 'fj'},
  fk: {name: 'Falkland Islands (Malvinas)', dial_code: '+500', code: 'fk'},
  fm: {name: 'Micronesia, Federated States of', dial_code: '+691', code: 'fm'},
  fo: {name: 'Faroe Islands', dial_code: '+298', code: 'fo'},
  fr: {name: 'France', dial_code: '+33', code: 'fr'},
  ga: {name: 'Gabon', dial_code: '+241', code: 'ga'},
  gb: {name: 'United Kingdom', dial_code: '+44', code: 'gb'},
  gd: {name: 'Grenada', dial_code: '+1 473', code: 'gd'},
  ge: {name: 'Georgia', dial_code: '+995', code: 'ge'},
  gf: {name: 'French Guiana', dial_code: '+594', code: 'gf'},
  gg: {name: 'Guernsey', dial_code: '+44', code: 'gg'},
  gh: {name: 'Ghana', dial_code: '+233', code: 'gh'},
  gi: {name: 'Gibraltar', dial_code: '+350', code: 'gi'},
  gl: {name: 'Greenland', dial_code: '+299', code: 'gl'},
  gm: {name: 'Gambia', dial_code: '+220', code: 'gm'},
  gn: {name: 'Guinea', dial_code: '+224', code: 'gn'},
  gp: {name: 'Guadeloupe', dial_code: '+590', code: 'gp'},
  gq: {name: 'Equatorial Guinea', dial_code: '+240', code: 'gq'},
  gr: {name: 'Greece', dial_code: '+30', code: 'gr'},
  gs: {name: 'South Georgia and the South Sandwich Islands', dial_code: '+500', code: 'gs'},
  gt: {name: 'Guatemala', dial_code: '+502', code: 'gt'},
  gu: {name: 'Guam', dial_code: '+1 671', code: 'gu'},
  gw: {name: 'Guinea-Bissau', dial_code: '+245', code: 'gw'},
  gy: {name: 'Guyana', dial_code: '+595', code: 'gy'},
  hk: {name: 'Hong Kong', dial_code: '+852', code: 'hk'},
  hn: {name: 'Honduras', dial_code: '+504', code: 'hn'},
  hr: {name: 'Croatia', dial_code: '+385', code: 'hr'},
  ht: {name: 'Haiti', dial_code: '+509', code: 'ht'},
  hu: {name: 'Hungary', dial_code: '+36', code: 'hu'},
  id: {name: 'Indonesia', dial_code: '+62', code: 'id'},
  ie: {name: 'Ireland', dial_code: '+353', code: 'ie'},
  il: {name: 'Israel', dial_code: '+972', code: 'il'},
  im: {name: 'Isle of Man', dial_code: '+44', code: 'im'},
  in: {name: 'India', dial_code: '+91', code: 'in'},
  do: {name: 'Dominican Republic', dial_code: '+1 849', code: 'do'},
  io: {name: 'British Indian Ocean Territory', dial_code: '+246', code: 'io'},
  iq: {name: 'Iraq', dial_code: '+964', code: 'iq'},
  is: {name: 'Iceland', dial_code: '+354', code: 'is'},
  ir: {name: 'Iran, Islamic Republic of', dial_code: '+98', code: 'ir'},
  it: {name: 'Italy', dial_code: '+39', code: 'it'},
  je: {name: 'Jersey', dial_code: '+44', code: 'je'},
  jm: {name: 'Jamaica', dial_code: '+1 876', code: 'jm'},
  jo: {name: 'Jordan', dial_code: '+962', code: 'jo'},
  jp: {name: 'Japan', dial_code: '+81', code: 'jp'},
  ke: {name: 'Kenya', dial_code: '+254', code: 'ke'},
  kg: {name: 'Kyrgyzstan', dial_code: '+996', code: 'kg'},
  kh: {name: 'Cambodia', dial_code: '+855', code: 'kh'},
  ki: {name: 'Kiribati', dial_code: '+686', code: 'ki'},
  km: {name: 'Comoros', dial_code: '+269', code: 'km'},
  kn: {name: 'Saint Kitts and Nevis', dial_code: '+1 869', code: 'kn'},
  kp: {name: 'Korea, Democratic People`s Republic of', dial_code: '+850', code: 'kp'},
  kr: {name: 'Korea, Republic of', dial_code: '+82', code: 'kr'},
  kw: {name: 'Kuwait', dial_code: '+965', code: 'kw'},
  ky: {name: 'Cayman Islands', dial_code: '+ 345', code: 'ky'},
  kz: {name: 'Kazakhstan', dial_code: '+7 7', code: 'kz'},
  la: {name: 'Lao People`s Democratic Republic', dial_code: '+856', code: 'la'},
  lb: {name: 'Lebanon', dial_code: '+961', code: 'lb'},
  lc: {name: 'Saint Lucia', dial_code: '+1 758', code: 'lc'},
  li: {name: 'Liechtenstein', dial_code: '+423', code: 'li'},
  lk: {name: 'Sri Lanka', dial_code: '+94', code: 'lk'},
  lr: {name: 'Liberia', dial_code: '+231', code: 'lr'},
  ls: {name: 'Lesotho', dial_code: '+266', code: 'ls'},
  lt: {name: 'Lithuania', dial_code: '+370', code: 'lt'},
  lu: {name: 'Luxembourg', dial_code: '+352', code: 'lu'},
  lv: {name: 'Latvia', dial_code: '+371', code: 'lv'},
  ly: {name: 'Libyan Arab Jamahiriya', dial_code: '+218', code: 'ly'},
  ma: {name: 'Morocco', dial_code: '+212', code: 'ma'},
  mc: {name: 'Monaco', dial_code: '+377', code: 'mc'},
  md: {name: 'Moldova, Republic of', dial_code: '+373', code: 'md'},
  me: {name: 'Montenegro', dial_code: '+382', code: 'me'},
  mf: {name: 'Saint Martin', dial_code: '+590', code: 'mf'},
  mg: {name: 'Madagascar', dial_code: '+261', code: 'mg'},
  mh: {name: 'Marshall Islands', dial_code: '+692', code: 'mh'},
  mk: {name: 'Macedonia, The Former Yugoslav Republic of', dial_code: '+389', code: 'mk'},
  ml: {name: 'Mali', dial_code: '+223', code: 'ml'},
  mm: {name: 'Myanmar', dial_code: '+95', code: 'mm'},
  mn: {name: 'Mongolia', dial_code: '+976', code: 'mn'},
  mo: {name: 'Macao', dial_code: '+853', code: 'mo'},
  mp: {name: 'Northern Mariana Islands', dial_code: '+1 670', code: 'mp'},
  mq: {name: 'Martinique', dial_code: '+596', code: 'mq'},
  mr: {name: 'Mauritania', dial_code: '+222', code: 'mr'},
  ms: {name: 'Montserrat', dial_code: '+1664', code: 'ms'},
  mt: {name: 'Malta', dial_code: '+356', code: 'mt'},
  mu: {name: 'Mauritius', dial_code: '+230', code: 'mu'},
  mv: {name: 'Maldives', dial_code: '+960', code: 'mv'},
  mw: {name: 'Malawi', dial_code: '+265', code: 'mw'},
  mx: {name: 'Mexico', dial_code: '+52', code: 'mx'},
  my: {name: 'Malaysia', dial_code: '+60', code: 'my'},
  mz: {name: 'Mozambique', dial_code: '+258', code: 'mz'},
  na: {name: 'Namibia', dial_code: '+264', code: 'na'},
  nc: {name: 'New Caledonia', dial_code: '+687', code: 'nc'},
  ne: {name: 'Niger', dial_code: '+227', code: 'ne'},
  nf: {name: 'Norfolk Island', dial_code: '+672', code: 'nf'},
  ng: {name: 'Nigeria', dial_code: '+234', code: 'ng'},
  ni: {name: 'Nicaragua', dial_code: '+505', code: 'ni'},
  nl: {name: 'Netherlands', dial_code: '+31', code: 'nl'},
  no: {name: 'Norway', dial_code: '+47', code: 'no'},
  np: {name: 'Nepal', dial_code: '+977', code: 'np'},
  nr: {name: 'Nauru', dial_code: '+674', code: 'nr'},
  nu: {name: 'Niue', dial_code: '+683', code: 'nu'},
  nz: {name: 'New Zealand', dial_code: '+64', code: 'nz'},
  om: {name: 'Oman', dial_code: '+968', code: 'om'},
  pa: {name: 'Panama', dial_code: '+507', code: 'pa'},
  pe: {name: 'Peru', dial_code: '+51', code: 'pe'},
  pf: {name: 'French Polynesia', dial_code: '+689', code: 'pf'},
  pg: {name: 'Papua New Guinea', dial_code: '+675', code: 'pg'},
  ph: {name: 'Philippines', dial_code: '+63', code: 'ph'},
  pk: {name: 'Pakistan', dial_code: '+92', code: 'pk'},
  pl: {name: 'Poland', dial_code: '+48', code: 'pl'},
  pm: {name: 'Saint Pierre and Miquelon', dial_code: '+508', code: 'pm'},
  pn: {name: 'Pitcairn', dial_code: '+872', code: 'pn'},
  pr: {name: 'Puerto Rico', dial_code: '+1 939', code: 'pr'},
  ps: {name: 'Palestinian Territory, Occupied', dial_code: '+970', code: 'ps'},
  pt: {name: 'Portugal', dial_code: '+351', code: 'pt'},
  pw: {name: 'Palau', dial_code: '+680', code: 'pw'},
  py: {name: 'Paraguay', dial_code: '+595', code: 'py'},
  qa: {name: 'Qatar', dial_code: '+974', code: 'qa'},
  re: {name: 'Réunion', dial_code: '+262', code: 're'},
  ro: {name: 'Romania', dial_code: '+40', code: 'ro'},
  rs: {name: 'Serbia', dial_code: '+381', code: 'rs'},
  ru: {name: 'Russia', dial_code: '+7', code: 'ru'},
  rw: {name: 'Rwanda', dial_code: '+250', code: 'rw'},
  sa: {name: 'Saudi Arabia', dial_code: '+966', code: 'sa'},
  sb: {name: 'Solomon Islands', dial_code: '+677', code: 'sb'},
  sc: {name: 'Seychelles', dial_code: '+248', code: 'sc'},
  sd: {name: 'Sudan', dial_code: '+249', code: 'sd'},
  se: {name: 'Sweden', dial_code: '+46', code: 'se'},
  sg: {name: 'Singapore', dial_code: '+65', code: 'sg'},
  sh: {name: 'Saint Helena, Ascension and Tristan Da Cunha', dial_code: '+290', code: 'sh'},
  si: {name: 'Slovenia', dial_code: '+386', code: 'si'},
  sj: {name: 'Svalbard and Jan Mayen', dial_code: '+47', code: 'sj'},
  sk: {name: 'Slovakia', dial_code: '+421', code: 'sk'},
  sl: {name: 'Sierra Leone', dial_code: '+232', code: 'sl'},
  sm: {name: 'San Marino', dial_code: '+378', code: 'sm'},
  sn: {name: 'Senegal', dial_code: '+221', code: 'sn'},
  so: {name: 'Somalia', dial_code: '+252', code: 'so'},
  sr: {name: 'Suriname', dial_code: '+597', code: 'sr'},
  st: {name: 'Sao Tome and Principe', dial_code: '+239', code: 'st'},
  sv: {name: 'El Salvador', dial_code: '+503', code: 'sv'},
  sy: {name: 'Syrian Arab Republic', dial_code: '+963', code: 'sy'},
  sz: {name: 'Swaziland', dial_code: '+268', code: 'sz'},
  tc: {name: 'Turks and Caicos Islands', dial_code: '+1 649', code: 'tc'},
  td: {name: 'Chad', dial_code: '+235', code: 'td'},
  tg: {name: 'Togo', dial_code: '+228', code: 'tg'},
  th: {name: 'Thailand', dial_code: '+66', code: 'th'},
  tj: {name: 'Tajikistan', dial_code: '+992', code: 'tj'},
  tk: {name: 'Tokelau', dial_code: '+690', code: 'tk'},
  tl: {name: 'Timor-Leste', dial_code: '+670', code: 'tl'},
  tm: {name: 'Turkmenistan', dial_code: '+993', code: 'tm'},
  tn: {name: 'Tunisia', dial_code: '+216', code: 'tn'},
  to: {name: 'Tonga', dial_code: '+676', code: 'to'},
  tr: {name: 'Turkey', dial_code: '+90', code: 'tr'},
  tt: {name: 'Trinidad and Tobago', dial_code: '+1 868', code: 'tt'},
  tv: {name: 'Tuvalu', dial_code: '+688', code: 'tv'},
  tw: {name: 'Taiwan, Province of China', dial_code: '+886', code: 'tw'},
  tz: {name: 'Tanzania, United Republic of', dial_code: '+255', code: 'tz'},
  ua: {name: 'Ukraine', dial_code: '+380', code: 'ua'},
  ug: {name: 'Uganda', dial_code: '+256', code: 'ug'},
  uy: {name: 'Uruguay', dial_code: '+598', code: 'uy'},
  uz: {name: 'Uzbekistan', dial_code: '+998', code: 'uz'},
  va: {name: 'Holy See (Vatican City State)', dial_code: '+379', code: 'va'},
  vc: {name: 'Saint Vincent and the Grenadines', dial_code: '+1 784', code: 'vc'},
  ve: {name: 'Venezuela, Bolivarian Republic of', dial_code: '+58', code: 've'},
  vg: {name: 'Virgin Islands, British', dial_code: '+1 284', code: 'vg'},
  vi: {name: 'Virgin Islands, U.S.', dial_code: '+1 340', code: 'vi'},
  vn: {name: 'Viet Nam', dial_code: '+84', code: 'vn'},
  vu: {name: 'Vanuatu', dial_code: '+678', code: 'vu'},
  wf: {name: 'Wallis and Futuna', dial_code: '+681', code: 'wf'},
  ws: {name: 'Samoa', dial_code: '+685', code: 'ws'},
  ye: {name: 'Yemen', dial_code: '+967', code: 'ye'},
  yt: {name: 'Mayotte', dial_code: '+262', code: 'yt'},
  za: {name: 'South Africa', dial_code: '+27', code: 'za'},
  zm: {name: 'Zambia', dial_code: '+260', code: 'zm'},
  zw: {name: 'Zimbabwe', dial_code: '+263', code: 'zw'}
};
